export const addInvoice = async (req, res) => {
    try {

    } catch (error) {
        console.log(error)
    }
}